import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full h-screen flex justify-center bg-gray-200 overflow-hidden">
        <div className="w-full max-w-[500px] bg-white overflow-y-scroll">
          <Navbar />
          <main className="p-4 ">{children}</main>
        </div>
      </body>
    </html>
  );
}
